### ISSUE TITLE
What do you know about "Chocolatey.org"

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/learn-flutter#11]
I was trying to solve issue #9 and I was doing some research on how I could get dart installed on the command line or powershell and of the few people I saw trying to install dart-sdk on the command line they all say it's necessary to install "Chocolatey" first.
I would like to know if anyone has ever used it or if they know what it's for.

**Comment by nelsonic** [comment]
@miguelmartins17 good question. 
What did you search for _`before`_ opening this issue? 
e.g: [https://github.com/search?q=org%3Adwyl+Chocolatey](https://github.com/search?q=org%3Adwyl+Chocolatey&type=Code)
People who use Windows in the wider @dwyl community have used and recommended Chocolatey
e.g: for [installing `elixir` on Windows](https://github.com/dwyl/learn-elixir/blob/35962518e7d6e5f8e5348fb56dc1844490da12e0/README.md#installation) see: https://github.com/dwyl/learn-elixir#windows

I have not used https://chocolatey.org _personally_ because I haven't used windows as my main computer since 2005 ... but it looks good https://github.com/chocolatey
![image](https://user-images.githubusercontent.com/194400/71766068-e90b8b80-2ef3-11ea-9f6d-9861cf453273.png)

Remember that the only people who will _see_ this question are the "Watchers" of this repository:
https://github.com/dwyl/learn-flutter/watchers
![image](https://user-images.githubusercontent.com/194400/71766083-06405a00-2ef4-11ea-9891-b81070542f70.png)

I know that @iteles hasn't used Windows since she left her last job in 2013 ... 
so she _definitely_ hasn't used Chocolatey. 😉 

If you want a response from a wider audience consider transferring this issue (_or opening a new one_) on [dwyl/technology-stack/issues](https://github.com/dwyl/technology-stack/issues) where there are more watchers ... 

Ultimately the people who use Windows for App Development (_mostly_) do so because they _have_ to. 
(_e.g. because they are building software for the Microsoft ecosystem or Games, etc. or because they work for a big company that is stuck using Windows because of [vendor lock-in](https://en.wikipedia.org/wiki/Vendor_lock-in) or inertia ..._)
Anyone who can _afford_ a Mac, has one. 
See: https://hackernoon.com/why-do-developers-run-macs-9ad81d58d177

The _only_ reason you (_Miguel_) have a Windows PC (beast desktop) is because that's what you _wanted_ for playing games and doing homework; otherwise you'd Mac the same way we got one for [Edu](@edwardcodes) 👨‍💻 
For doing the _creative work_ that pays _really well_ that we do @dwyl, nothing beats a Mac.
There is an **i7 MacBook Air** sitting on my desk waiting for you when you want to join us. 😉

**Comment by miguelmartins17** [comment]
Chocolatey is a package manager for Windows. Similar to Linux tools like apt or yum, but designed specifically for Windows, Chocolatey was designed to be a decentralized framework for quickly installing applications and tools that you need.

@nelsonic When you want to borrow the PC (Mac) to start working with the IOS applications and to start working with Swift I am open to new challenges.
I'm ready to join you on the Mac whenever you want.
