### ISSUE TITLE
Flutter VS Xamarin

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/learn-flutter#18]
Flutter and Xamarin are both cross-platform mobile application development frameworks used to build apps using a single code base.
I have been researching more information that might be important about Flutter and I have a friend who is in college studying Xamarin and I asked him if he knew Flutter and he said no.
I was wondering which one is most used now and which is the best.

**Comment by miguelmartins17** [comment]
I leave you here the link:
https://blog.codemagic.io/flutter-vs-xamarin-a-developer-s-perspective/

**Comment by nelsonic** [comment]
@miguelmartins17 these are all valid questions 👍 
but "_which one is the best_" without giving precise criteria will always/only lead to an _opinion_ based answer. 
You want to _avoid_ being swayed by _opinion_ as much as possible and try to focus on facts.

Xamarin has been around for a _long_ time https://en.wikipedia.org/wiki/Xamarin it was founded in 2011.
If you scroll through the list of companies/apps using Xamarin, you will notice it's very "corporate":
https://dotnet.microsoft.com/apps/xamarin/customers
![image](https://user-images.githubusercontent.com/194400/72690260-82e95000-3b12-11ea-8dc1-cff081c65ab3.png)
That's a _good_ sign if your objective is working for a _big_ company on _incredibly boring_ Apps. 😴  

Xamarin has always been a _paid_ and _closed source_ product which limited the adoption considerably.
see: https://www.quora.com/How-much-does-Xamarin-cost

Microsoft bought the company in 2016 and has been integrating their tools into MSFT's stack.
see: https://dotnet.microsoft.com/apps/xamarin
![image](https://user-images.githubusercontent.com/194400/72690170-803a2b00-3b11-11ea-9e27-78814c204a8d.png)

The SDK was only _recently_ open sourced after the Microsoft acquisition.
Which means you can use it to build apps without paying them to use the SDK ...
This is Microsoft's effort to increase adoption in the face of competition from [React Native](https://github.com/dwyl/learn-react/issues/23) and now Flutter ... Not _that_ many people want to write apps in **`C#`** (_when compared to JS_) ... and if you look at the **growth rate** for ***`Dart`*** on GitHub https://octoverse.github.com/#top-languages there is good reason to believe that Flutter will _dominate_ the landscape for cross-platform native mobile apps in 2020+!
![image](https://user-images.githubusercontent.com/194400/72689900-5af7ed80-3b0e-11ea-85b4-84fd3a6e75dd.png)

The _reason_ why _some_ learning institutions still use/teach Xamarin is because Microsoft has an extremely _aggressive_ sales force pushing their tech to people at the learning phase so that they then take it with them to industry. There's a _reason_ most schools use Microsoft Windows/Office and it's _definitely not_ because the _software_ is "_better_" ... Microsoft "_pushes_" their tech into schools like a [drug pusher](https://en.wiktionary.org/wiki/drug_pusher) to get kids addicted to their product. 

Meanwhile, back to Xamarin ... you _can_ use it for "free" by using the "community edition" of visual studio provided you are an Individual or open source projects. (_so technical @dwyl would qualify_)
But for any _business_ wanting to use it, they _must_ pay at _least_ $45/user/month 
i.e. for a "small" team of say 10 people it would be $5400/year ... 💸 
https://visualstudio.microsoft.com/vs/pricing

![image](https://user-images.githubusercontent.com/194400/72689836-b70e4200-3b0d-11ea-9917-9714c9df19e7.png)

The reason I would _never_ even _consider_ Xamarin is that it locks you into the Microsoft ecosystem.
And I cannot think of anything _worse_ than being _married_ to Microsoft! 🤮
Microsoft is an Evil company that achieved their dominance through coercion and intimidation. read:
https://www.reddit.com/r/OutOfTheLoop/comments/2v4ses/why_is_microsoft_so_widely_considered_evil
It's the same reason you'll never see an XBox [@home](https://github.com/dwyl/home) or any Windows PCs (_other than test machines_). 

_Thankfully_, (_for the purposes of this discussion of Flutter vs. Xamarin..._) it appears that Xamarin are _not_ adding **Web** support to their platform.  (_I would have thought it would be **easy** for them to add it, but they aren't doing it because it would **compete** with Microsoft's ASP.NET platform ... which is a major ["**cash cow**"](https://en.wikipedia.org/wiki/Cash_cow)_). That means if we used Xamarin to build the @dwyl "native" mobile app, we would still need to build a _separate_ Web version. That's _exactly_ the duplication of effort we are trying to avoid! 🤦‍♂ 

I wouldn't use Xamarin even if it was _objectively_ "better" than Flutter. 
I consider this "Flutter VS Xamarin" not relevant to @dwyl (_for the reasons stated above_).
This might be "stubbornness" ... but I feel that Microsoft _still_ goes against @dwyl's [core principals](https://github.com/dwyl/start-here/blob/master/manifesto.md). 

I am _open minded_ about _most_ things, but _not_ Microsoft. 
They still use aggressive/monopolistic sales tactics to perpetuate ["vendor lock-in"](https://en.wikipedia.org/wiki/Vendor_lock-in) 
see: https://en.wikipedia.org/wiki/Criticism_of_Microsoft#Vendor_lock-in
Vendor lock-in is great for MSFT shareholders but _horrible_ for customers.
There are _laws_ against [Anti-competitive practices](https://en.wikipedia.org/wiki/Anti-competitive_practices) for a _reason_; they are bad for _society_. 
Microsoft is the _textbook definition_ of anti-competitive. 
History lesson reading: 
+ https://en.wikipedia.org/wiki/Robber_baron_(industrialist)
+ https://en.wikipedia.org/wiki/United_States_v._Microsoft_Corp.

_Other_ people should use whatever they are familiar with and can get paid for. ✅ 
If you (Miguel) feel that it will improve your prospects of getting a job, 
you should learn it (_in your spare time_) ... especially if you have a friend who can help you.


The _conclusion_ of the codemagic post is _useless_: 
![image](https://user-images.githubusercontent.com/194400/72690560-5edb3e00-3b15-11ea-9a70-9760fc429bef.png)
A "_conclusion_" without a _recommendation_ is a waste of time.
The point of a _comparison_ is to help people make a _decision_, not to say "_Xamarin and Flutter are two players in the cross-platform mobile development market_" which we all already knew!! 🤦‍♂ 

I don't think you will get an _objective_ answer (_without opinion_) on any internet forum. 
So once you have made up your mind, please _close_ this issue. 
Thanks! 👍

**Comment by miguelmartins17** [comment]
@nelsonic Thanks for your answer, you're really right I could never want a concrete answer through opinions.
And Flutter is being much more exploited than Xamarin, I find it very strange that colleges choose to explain old things to students.
