### ISSUE TITLE
What Flutter and React Native have in common ?

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/learn-flutter#20]
While looking more about Flutter/Dart I noticed that many times React Native is mentioned, is there any connection between them ? Is it worth exploring more about React Native ? Is it a good bet of our time to write about the differences between them ? 💭

**Comment by nelsonic** [comment]
@miguelmartins17 this is a _good_ question. You will _often_ hear people _compare_ and _contrast_ these two technologies because they have _similar_ goals/objectives: Build Cross-Platform Native Mobile App.

> We can let _other_ people write about the differences between React Native and Flutter. 
> For now we only _care_ about learning about Flutter. 

For context:
We were _required_ to use React Native for an IOS App for client in 2018 and it was a _nightmare_! 
The process of compiling a React Native app was _painfully_ slow (_like 20 mins each time_) it took _ages_ to build features and then when it came time to attempt to deploy the app to the Google Play we discovered that 30-50% of the App would need to be re-written because the UI was not "standard". 
This StackOverflow question (_without any solution 22 months later_) summarises our pain: https://stackoverflow.com/questions/49436853/slow-compile-react-native-ios-app
We had an App with 100+ screens and reasonably complex interaction. It took 20+ mins to compile!
Slow compile times are a known issue: https://github.com/facebook/react-native/issues/25030 ... But when FB don't have a solution to a problem they simply _close_ the issue and "lock" it so that it cannot be re-opened. 🔒 

We ended up having to rebuild the App in `Elm` as a Web App, which was _much_ faster and worked _everywhere_. The Elm Web App was then "wrapped" in a Web View. 
(_that's why I opened the Web View SPIKE #5 to see how easy it was to "wrap" a Web App ..._)

I would not use React Native again in any time soon it's **_substantially_ inferior** to Flutter.
The _reason_ I'm interested in Flutter is that _all_ the Material UI widgets are created by Google.
So not only are they _fast_ to compile, they are _consistent_ across devices/platforms.
The only reason React Native is more _popular_ than Flutter right now is that RN was available earlier.
Flutter will take the place of React Native as the preferred cross-platform app development system in the next 18 months. Be _ahead_ of the curve by becoming an _expert_ in Flutter.
Then if you end up applying to work for a _different_ company (_not @dwyl_) you can pick up RN in a couple of weeks so that you know what you're getting into ... 👍
