### ISSUE TITLE
 KlasterMe App built with Flutter

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/learn-flutter#21]
Now in the afternoon a friend of mine sent me an application saying that he was being more and more popular and installed in the university where he is.
Out of curiosity I went to see what the application was like and what it was for and then after researching several things about the application I noticed that the application was built using Flutter which is quite positive for us because it means that more and more applications are being recognized made in Flutter.
It gives us another perspective of public acceptance about the applications.
Learning Flutter has been a very interesting experience as I've learned a lot in the last few weeks, really running Flutter applications is very fast compared to Android applications, the installation is very simple on Windows and even with a little more difficulty it is easy to get to the end on Mac.

**Comment by miguelmartins17** [comment]
This is the App:


![8bvQX1B2Fk](https://user-images.githubusercontent.com/27420533/73025148-f519a780-3e26-11ea-8659-6af161f62a29.png)

**Comment by nelsonic** [comment]
@miguelmartins17 thanks for sharing. 👍 
This reminds me that we need a better channel for sharing "_interesting_" things.
And also a better way of sharing information with more _analysis_. 
Did you _download/install_ the app to `try` it out?
Is there an _analysis_ of the features/functionality anywhere? 

The website is good looking but fairly generic ...
![image](https://user-images.githubusercontent.com/194400/73080993-b2a3a980-3ebe-11ea-88ac-168686e000a1.png)
I cannot determine how it's _better_ than existing content sharing platforms ... 💭 
Why would someone use this instead of Reddit or Twitter for example?
(_**Note**: I'm not saying that KlasterMe is "**bad**" I just don't understand the [USP](https://en.wikipedia.org/wiki/Unique_selling_proposition) ..._)

### "Popularity" is always _relative_ ...

At the bottom the website https://www.klasterme.com, there are links to _other_ social networks: 
![klasterme-social-links](https://user-images.githubusercontent.com/194400/73074278-2b036e00-3eb1-11ea-9417-02f15369150a.png)


If you click on the _facebook_ one https://www.facebook.com/klasterme you'll notice **93** "likes":
![klasterme-facebook](https://user-images.githubusercontent.com/194400/73060676-47db7980-3e90-11ea-8553-62805a39d72a.png)
The creators of the app probably have more than 93 _friends_ they could ask to "like" their app to boost it's popularity on the Fb ... 💭 

Their insta https://www.instagram.com/klastermeapp might look slightly better on the _surface_:
![image](https://user-images.githubusercontent.com/194400/73074571-d9a7ae80-3eb1-11ea-8831-50c38b775d96.png)

But we _all_ know that it's _very easy_ to _buy_ Insta followers & interactions so the number is _meaningless_. 
https://www.vox.com/2014/9/11/7577585/buy-instagram-followers-bloggers

There posts appear to be **stock photos**: (_or great looking photos from their community?_)
![image](https://user-images.githubusercontent.com/194400/73074754-399e5500-3eb2-11ea-9b94-b2d79ddb9ee9.png)

Lots about their photography competitions, but not much about using the _App_ ... 
What _exactly_ are they building?

Their most recent post https://www.instagram.com/p/BzatqyRpTKH was 29 weeks ago ... 
![image](https://user-images.githubusercontent.com/194400/73065299-27fd8300-3e9b-11ea-9216-9fde418fdbb2.png)
That's a _really_ long time online ... 

Similar story on Twitter https://twitter.com/klasterme very little and generic content and low interaction.
![image](https://user-images.githubusercontent.com/194400/73080329-8e939880-3ebd-11ea-82f1-f68d1a21f360.png)


### Native App Adoption

https://apps.apple.com/us/app/klasterme/id1447766950
![image](https://user-images.githubusercontent.com/194400/73079462-2db79080-3ebc-11ea-88fb-3463ff8450b7.png)
Not many users/reviews for iOS ... 

Google Play has a few more:
https://play.google.com/store/apps/details?id=com.wecslabs.klasterme
![image](https://user-images.githubusercontent.com/194400/73079472-34de9e80-3ebc-11ea-9e38-ddd15a11c6e3.png)
Reviews:
![image](https://user-images.githubusercontent.com/194400/73079582-6192b600-3ebc-11ea-82ad-c82b680a96c4.png)
![image](https://user-images.githubusercontent.com/194400/73079631-796a3a00-3ebc-11ea-9229-63ca01d5c733.png)
Again, remember that it's also _easy_ to buy "***installs***", especially in lower cost economies. 
https://keyapp.top/buy-app-installs
![image](https://user-images.githubusercontent.com/194400/73083779-ae2dbf80-3ec3-11ea-9803-fc63f7073989.png)
![image](https://user-images.githubusercontent.com/194400/73083797-b84fbe00-3ec3-11ea-9465-46402f7be70b.png)
This **_fake_ popularity** is _pointless_. It's a _waste_ of money and does not improve the _product_ at all.
I _understand_ the temptation for a "social" app to buy Insta followers or Android installs to _appear_ to be popular, but it's_ far_ better to just focus all efforts on building something that is [_remarkable_](https://en.wikipedia.org/wiki/Purple_Cow:_Transform_Your_Business_by_Being_Remarkable).  

A bit more insight on https://appgrooves.com/app/klasterme-by-wecs-labs-inc
![klastereme-appgrooves](https://user-images.githubusercontent.com/194400/73074958-add8f880-3eb2-11ea-809e-0e41c266a8af.png)
Not a lot of _genuine_ traction ... did the _friend_ who sent you KlasterMe actually _use_ the app?
If KlasterMe do not offer a _significant_ innovation over rival platforms, they may need to [**pivot**](https://github.com/dwyl/start-here/issues/196) soon. 

## Conclusion ?

This App might built with Flutter and that's _good_. 👍 
But it's not a good _showcase_ of Flutter _features_. 😕 
I think the best _showcase_ is actually the Google _Stadia_ Game Platform. 🎮 
And there are _many_ others on: https://flutter.dev/showcase 💡 
(_yes, Stadia is not yet available in PT, so we aren't able to test it, 😞 
but the fact Google have built a game rendering engine in Flutter/Dart is **epic**!_) 🎉 

<hr />

Miguel, as for your _learning_ of Flutter, it's great that you have learned a lot.
Please _share_ your learning and write **`code`** with your knowledge. 
![last-update-4-days-ago](https://user-images.githubusercontent.com/194400/73087525-8a21ac80-3eca-11ea-87b3-776e51b392ee.png)
This repo was last updated **4 days ago** ... 
What have you been _doing/learning_ for the last 4 days? 🤔 
I'm _excited_ that you have chosen to become a developer 
instead of applying for shallow work jobs ...
but you **_must_ push yourself** to **learn _faster_**. 
Please read: https://github.com/dwyl/apprenticeship

<hr />

Closing this issue as it's not strictly relevant to learning Flutter. 
There is no **`code`** available for KlasterMe App so we cannot learn much from it.
The only reference to I could fund to KlasterMe on GitHub is: https://github.com/abinmittu
![image](https://user-images.githubusercontent.com/194400/73088202-abcf6380-3ecb-11ea-88dc-9761f8fae539.png)
Not much I can _learn_ from this ...
