### ISSUE TITLE
New Repository Google Sign In with Flutter 

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/learn-flutter#22]
We should create another repository to explain how to do the Sign In with Google using Flutter (Without using Firebase).
It would be good to create a tutorial on this since the topic of Sign In has been addressed many times without using Firebase.

**Comment by nelsonic** [comment]
@miguelmartins17 this could be relevant _after_ https://github.com/dwyl/flutter-todo-list-tutorial/issues/2 👍 
(_Google Sign In is not required for the Todo List Tutorial_)

**Comment by nelsonic** [comment]
Longer answer ...

I've _just_ logged into the Figma desktop app via what I am 100% sure was a WebView. 

When I clicked the **login** button in the **Native Desktop App**:

![figma-desktop-login-buton](https://user-images.githubusercontent.com/194400/73340872-6caa6500-4273-11ea-85b3-712b8b1798c5.png)

![figma-desktop-instructions](https://user-images.githubusercontent.com/194400/73340934-88157000-4273-11ea-8b4c-5d4ba8571ec4.png)

it opens a Web Browser: (_so the Auth is **NOT** implemented in the **Native App**_)

![figma-web-view-login](https://user-images.githubusercontent.com/194400/73341015-af6c3d00-4273-11ea-9911-5bd13fbf1d68.png)

Click on "Log in with Gogle"
![image](https://user-images.githubusercontent.com/194400/73341263-2f92a280-4274-11ea-8001-d0c24414c387.png)

Still in a Web Browser:
![image](https://user-images.githubusercontent.com/194400/73341284-391c0a80-4274-11ea-9779-8ab9ef7dcb35.png)


After I authenticated with my Google Account this is what I see: 
![image](https://user-images.githubusercontent.com/194400/73341349-62d53180-4274-11ea-9140-433468490f4a.png)

I have to click a Button "**Open Desktop App**" to re-directed back to the desktop app. 

An alert appears asking me to _confirm_ that I want to Open **Figma.app**
![image](https://user-images.githubusercontent.com/194400/73341501-a4fe7300-4274-11ea-9ef3-da9d5af442a4.png)

Now I am logged in and can see my wireframe in the Native Desktop App.
![image](https://user-images.githubusercontent.com/194400/73341644-f4dd3a00-4274-11ea-827f-26883f378589.png)


So I _know_ that it's possible to use our [Elixir Auth Google](https://github.com/dwyl/elixir-auth-google) (Server-side Auth) 
and ***redirect*** back to a Flutter App. 
This is 100% how we are going to implement Auth in our Native App. 
We do _not_ need to re-invent Auth in Dart. 
If you don't understand how this works behind the scenes, don't worry about it!
I will write the code including tests and _detailed_ documentation so _everyone_ understands.

_Please_ focus on the Flutter Todo List Tutorial Task dwyl/flutter-todo-list-tutorial#2
We need a _comprehensive_ Flutter Todo List Tutorial that a _complete_ beginner can understand and learn from so that 100+ @dwylers can learn how to use Flutter. 
Until the Flutter Todo List Tutorial is _complete_ (_without any authentication_),
we don't need to _think_ about Auth in a Flutter App. 
We will **`continue`** building the Phoenix app: https://github.com/dwyl/app-mvp-phoenix
Which will _become_ the Realtime API used by the Native App (_when we build it..._)

Hope that answers your question or at least directs your focus back to the task. 👍

**Comment by miguelmartins17** [comment]
I remain focused on learning how to make a real tutorial with everything necessary to pass all the knowledge acquired about Flutter. 
I just thought it would be necessary to learn git and how to really use Github, in order to be more productive.
I continue to use the tutorials and documents in [dwyl/start-here](https://github.com/dwyl/start-here#git--github) to deepen my knowledge and make my experience with Git easier.

 Even following the Tutorial done in Javascript there are still some doubts about how to proceed to make a useful tutorial so that everyone can really learn Flutter without doubt. 😕

**Comment by nelsonic** [comment]
@miguelmartins17 learning Git/GitHub is indeed _required_ for doing _most_ `dev` work. :octocat: 
(_that's why it's listed in the [**`How?`**](https://github.com/dwyl/start-here#git--github) of "start-here"_) 👍 
Please **`continue`** to ask _questions_ in the _specific_ repositories when you have doubts. ❓ 
The way to proceed is to ***imitate*** the _existing_ Javascript Todo List Tutorial. 

## "_Imitation is not just the sincerest form of flattery - it's the sincerest form of learning._" ~ George Bernard Shaw
 
_Follow_ the checklist in dwyl/flutter-todo-list-tutorial#2, _build_ the app  and _document_ every step along the way, the same way that I have shown the Javascript Todo List Tutorial.

The most difficult part _might_ be writing _automated_ tests which you have _less_ experience with.
(_but that's the whole point of meticulously following the Javascript Todo List Tutorial which shows TDD_)

Thankfully there are a few _really_ good videos on the Flutter YT channel for testing. e.g:

[![image](https://user-images.githubusercontent.com/194400/73355861-f61c6000-4290-11ea-93d6-00de16962bb6.png)](https://youtu.be/bj-oMYyLZEY)
https://youtu.be/bj-oMYyLZEY

But if you reach an **_impassable_ obstacle** (_or something that you feel is impossible to understand/achieve_), _please_ leave a comment in the issue (_or open a new one_) ***immediately*** so that we can _help_ you overcome it. There are no [**immovable objects**](https://youtu.be/9eKc5kgPVrA) that cannot be overcome when you are an [**unstoppable force**](https://en.wikipedia.org/wiki/Irresistible_force_paradox). Your biggest "super power" as a Developer is not _coding_, it's _communication_! 💡
