### ISSUE TITLE
How will the connection between Flutter and Phoenix be made? 

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/learn-flutter#25]
I would like to know more about this because I never understood how the connection between the two could be made.

**Comment by nelsonic** [comment]
@miguelmartins17 good question. The Flutter App will make HTTP Requests to the Phoenix REST API.
That's why I created #6 to test how easy/difficult it is to make a REST API request. 👍 
Once we have got the REST Requests working we will need to implement WebSockets for "real time" interactions. Phoenix's "superpower" is making WebSockets _easy_. 
See: https://flutter.dev/docs/cookbook/networking/web-sockets

**Comment by miguelmartins17** [comment]
Now I understand how it's gonna work. Thank you! 👍
