### ISSUE TITLE
Splash Screen Page

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/learn-flutter#26]
What do you think about starting the application with a splash screen with the dwyl logo followed by the login ?

**Comment by nelsonic** [comment]
When building the "onboarding" process in an App our objective is to _minimise_ the number of steps between someone first discovering the App and being able to interact with it effectively.

When you _first_ play a video game like Super Mario or Tetris there are no _detailed_ instructions telling you _how_ to play. There are design cues or clues which make it almost _immediately_ obvious what you need to do:

[![image](https://user-images.githubusercontent.com/194400/74088327-161c0280-4a8d-11ea-80d6-b4335113e272.png)](https://youtu.be/La2aGhZxLkQ)
https://youtu.be/La2aGhZxLkQ

[![image](https://user-images.githubusercontent.com/194400/74088980-0eac2780-4a94-11ea-895c-540c0f17f1a6.png)](https://youtu.be/K-NBcP0YUQI)

Without any _text_ telling you what to do, you instantly know what to do in Super Mario. 
The onboarding UX of the game is _so_ good that you don't even _notice_ it. You just _play_!
If our UI/UX is _needs_ text instructions we have _failed_.

<hr />

The link you have shared above is blog post on MockPlus, a mockup tool who are trying to _sell_ you on using _their_ tool. They have vested interest in perpetuating _complexity_ as a justification to use their tool.

**Question 5** in the blog post is "***Do you use Mockplus***?"
![this-is-an-advert](https://user-images.githubusercontent.com/194400/74090233-ebd44000-4aa0-11ea-93df-d26b7e2efcba.png)

What has that got _anything_ to do with **homepage design**? 🤷‍♂ 
You've just spent your time reading an Advert. 
Remember: ["**_All_ ads _lie_**!"](https://youtu.be/eP_Pb-ou1-Q)
The _moment_ you notice that "content" is actually trying to _sell_ you something you should _immediately_ close it and not trust the source. It's ["***avertorial***"](https://en.wikipedia.org/wiki/Advertorial) not a _real_ blog post from someone with _experience_ of building Apps.
Scroll down to the _author_ of the post:
![summer-ye](https://user-images.githubusercontent.com/194400/74090293-67ce8800-4aa1-11ea-96bd-76d8a33335d9.png)
I mean no disrespect to Summer, but they are an "SEO content writing" i.e. they work in _marketing_.
That is not someone who as actually _built_ any apps with any level of success. 
They are "_researching_" and writing the post in order to generate clicks. 


### A Note on Mockup tools:

Mockup tools are not used to actually _build_ the product, they are a way for self-indulgent "designers" to show off all the _amazing_ features the product _could_ have. But rather than being a _good_ use of the team's time, over-complicated designs is a _distraction_ from focussing on building what the _users_ want.
Having fancy designs/mockups is a "red flag" in a startup because it shows they are spending _way_ too much time dreaming about _potential_ features and nowhere _near_ enough time _building_ useful things!  ALL the startups that _fail_ (i.e. 95%) have amazing mockups/designs and no 

## Mockups = [Vaporware](https://en.wikipedia.org/wiki/Vaporware)

Mockups aren't _real_, they are a distraction from the _real_ work that _hasn't_ been done; writing **`code`**!

### 5 Questions ...

Let's dive a bit deeper into these "***5 questions that the homepage should answer***"; they aren't _all_ bad.

#### Question 1: Who are you?

While I _agree_ this is a nice question to have an _answer_ to because it encourages [transparency](https://github.com/dwyl/start-here/blob/master/manifesto.md#full-transparency) 🎉 
but honestly _when_ was the last time you thought to yourself:
"_I don't know **Who** WhatsApp is so I won't use the App_"

This is _not_ a question that very many people _actually_ care about when deciding to use a product/App.
Otherwise they would have taken a _moment_ to think about ***Who*** is behind [Facebook](https://github.com/dwyl/learn-react/issues/23#issuecomment-426007416) and _immediately_ ***`delete`*** the App! 

#### Question 2: What can you do?

This is probably the most _relevant_ question in the post. 
But right under the question I am _subjected_ to an obnoxious advert!!

![annoying-advert](https://user-images.githubusercontent.com/194400/74090547-779b9b80-4aa4-11ea-89e7-8e6eb13de57b.png)

Back to the question though ...
What an App can ***do*** for you should have _already_ been _obvious_ from what you _searched_ for.
Let's say you went searching for an App to keep track of your "lifts" in the gym.
What would you search for? "Gym tracking". 
And in the search results you see: 
![image](https://user-images.githubusercontent.com/194400/74090569-c34e4500-4aa4-11ea-8603-1c8b8a97cc6e.png)
Do _any_ of these apps still need to ***explain*** what they can **do** for you? 
No! 
You open the App and start _using_ it.

It _must_ be the same for _our_ App. It must be _immediately_ obvious what can be done with the App.
Otherwise our UX has _failed_.


#### Question 3: What information can you provide?

Totally irrelevant to _our_ App.
We are not providing any "information".
We are providing a way for people to organise their lives and be more effective with their time.


#### Question 4: How do you plan the layout?

Now we're back to pitching the Mockup tool ... 🤦‍♂ 
Of _course_ an App plans the layout this is _obvious_ and has _nothing_ to do with "Home page design".

... 

Finally question 5, as described above is just an ***`Ad`*** which invalidates the rest of the post.

<hr />

Let's not get too distracted by Splash Screens ... there is a _lot_ of other work to focus on. 

Always remember:

### “_Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away_.” ~ Antoine de Saint-Exupéry

If we don't _need_ a splash page we will not _make_ one.
